apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: image-registry.openshift-image-registry.svc:5000/ocp-example-node-app-images/example-app:latest
    newTag: "0815eaeef3ccfc854b23204db5228c329b0628c3"
patches:
  - path: route-patch.yaml
    target:
      kind: Route
      name: example-app
