apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- active-route.yaml
images:
 - name: image-registry.openshift-image-registry.svc:5000/ocp-example-node-app-images/example-app:latest
   newTag: "0.0.11"
patches:
- path: route-patch.yaml
  target:
    kind: Route
    name: example-app
