apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  workspaces:
  - name: repo
  - name: git-credentials
  params:
  - name: APP_NAME
    type: string
  - name: GIT_REPO
    type: string
  - name: GIT_REVISION
    type: string
  - name: IMAGE_NAME
    type: string
  - default: .
    name: PATH_CONTEXT
    type: string
  tasks:
  - name: fetch-repo
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: repo
    - name: ssh-directory
      workspace: git-credentials
  - name: build
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    - name: TLSVERIFY
      value: "false"
    - name: CONTEXT
      value: $(params.PATH_CONTEXT)
    runAfter:
    - fetch-repo
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: repo
  - name: update-image-tag
    params:
    - name: IMAGE_NAME
      value: $(params.IMAGE_NAME)
    taskSpec:
      workspaces:
      - name: source
        description: A workspace that contains the file which needs to be altered.
      params:
      - name: IMAGE_NAME
        type: string
    runAfter:
    - build
    workspaces:
    - name: source
      workspace: repo
  - name: push-repo
    params:
    - name: GIT_USER_NAME
      value: PIPELINE
    runAfter:
    - update-image-tag
    taskRef:
      kind: ClusterTask
      name: git-cli
    workspaces:
    - name: source
      workspace: repo
    - name: ssh-directory
      workspace: git-credentials
